before_install: git clone https://github.com/testify/build-settings.git target/travis
install: mvn install --quiet -DskipTests=true -B --settings target/travis/settings.xml""
script: mvn test --quiet -B --settings target/travis/settings.xml
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn deploy --settings target/travis/settings.xml'
language: java
jdk:
  - oraclejdk7
